### PR TITLE
Feature/rest service

### PR DESCRIPTION
**Pull request by NRBPerdijk**
Intruduces a REST Service currently integrated with the rule-viewer Play project. It allows users to use JSON to send messages to a service endpoint to fire up their businessrules and get their results (and the initial values). For now, only the runAll endpoint is available, which will let the rule engine perform all evaluations for which it has sufficient input and which it can find in the target project.

Example JSON message body for request and response: 
`{
"nameOfFactOfTypeString": "factValue",
"nameOfFactOfTypePercentage": 1234,
"nameOfFactOfTypeBedrag": 1234,
"nameOfFactOfTypeBigDecimal": 1234
}`

It provides integrated conversions for Facts of type Bedrag, BigDecimal, String and Percentage to and from Json and projects can expand or overwrite on these types by extending the JsonConversionsProvider with the proper conversion mapping.

Wrongly formatted Json, Fact names that cannot be found in the provided project's glossary and factValues provided in the wrong Json format (i.e. a JsString for a numeric fact) will result in a BadRequest containing Json detailling the problem.

A request containing no issues will result in an Ok, containing Json with both the initial facts and values (input), and the derived facts and values (results). For now, these have not been separated.

### CODE REVIEW

**Comment by NRBPerdijk** [comment]
Please don't merge in though, will look for a way to make this a stand-alone integratable component.

**Comment by jhkuperus** [comment]
Don't worry :) We'll have some lengthy brainstorm sessions first ;) I'll review this in the coming weekend.

**Comment by NRBPerdijk** [comment]
Closing pull request: the REST service has been moved to its own repository: [](https://github.com/scala-rules/rule-rest)

**Comment by NRBPerdijk** [comment]
[REST repo](https://github.com/scala-rules/rule-rest)

**Pull request closed without merging**
